### ISSUE TITLE
You can't have both node-red-contrib-postgres and node-red-contrib-postgres-multi at the same time

### ISSUE THREAD

**Issue by pokryva** [BruceFletcher/node-red-contrib-postgres-multi#1]
It seems that you can't have both node-red-contrib-postgres and node-red-contrib-postgres-multi at the same time, because, according to NR logs:

`[warn] [node-red-contrib-postgres-multi/PostgreSql] 'postgres' already registered by module node-red-contrib-postgres`

And I can confirm, that in the nodes palette there's only one node - in my case ode-red-contrib-postgres, as it was installed first.

NodeRED 0.18.4

**Comment by BruceFletcher** [comment]
First of all, thank you for trying out this module!

Yes you are correct, you can only use one postgres module or the other. This is described in the 'compatibility' section of the project readme.

My design assumption is that making the modules easier to migrate between is more valuable than being able to have two different postgres modules with different query semantics in the same project. If that doesn't seem to make sense, please describe how you would want the modules to work together.

**Comment by BruceFletcher** [comment]
I think there might be a bigger issue here with my design decision; it seems to be really hard to get Node-RED to accept this module as a replacement for the original node-red-contrib-postgres.

I guess I'll probably have to give it internally independent names and accept that migrating between the two will be that much harder.

**Comment by pokryva** [comment]
I can only apologize for not reading node's readme thoroughly - my bad.
You, as a creator of the node should have full freedom to design your node however you like, but on the other hand us - users - should also have the same freedom in choosing which nodes to use for which tasks :) Yeah, that came up very philosophical ;)
Anyways - I think that it's up to you, but I am also happy that this discussion allowed you to give your  creation a second glance ;)
